### ISSUE TITLE
Cut and copy character limit

### ISSUE THREAD

**Issue by JanBakker88** [MicrosoftDocs/IntuneDocs.nl-nl#100]
Hi,

I do not see the "cut and copy character limit" section.

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 3de6ad12-fbb8-3edf-4606-3ab3930efc74
* Version Independent ID: f886abd1-ee59-ac18-d0fe-a6d0c7066464
* Content: [Instellingen voor beveiligingsbeleid voor Android-apps](https://docs.microsoft.com/nl-nl/intune/app-protection-policy-settings-android)
* Content Source: [intune/app-protection-policy-settings-android.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/app-protection-policy-settings-android.md)
* Service: **microsoft-intune**
* Product: ****
* Technology: ****
* GitHub Login: @Erikre
* Microsoft Alias: **erikre**

**Comment by CeciAc** [comment]
Hello, @JanBakker88
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JanBakker88
 
We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @JanBakker88
 
Thanks once again for your comment.
Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future.

Kind regards,
Microsoft DOCS International Team
