### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by bruun365** [MicrosoftDocs/IntuneDocs.nl-nl#105]
Typo: Micro soft Defender firewall (remove space between Micro & soft)

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 6cbb1c16-4ed4-42d2-0b3f-ce4311e52637
* Version Independent ID: 8f8d6e3d-d6d6-bde9-4f16-6fc25d9be52a
* Content: [Beveiligingsinstellingen voor Windows 10-apparaten in Microsoft Intune - Azure](https://docs.microsoft.com/nl-nl/intune/protect/endpoint-protection-windows-10#feedback)
* Content Source: [intune/protect/endpoint-protection-windows-10.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/protect/endpoint-protection-windows-10.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by srvbpigh** [comment]
Hello, @bruun365
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @bruun365,  

  

Thank you for your feedback. 

  

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/nl-nl/intune/protect/endpoint-protection-windows-10#feedback.  

 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

 

Kind regards, 

Microsoft DOCS International Team
