### ISSUE TITLE
DEP v.s. DEM

### ISSUE THREAD

**Issue by JanBakker88** [MicrosoftDocs/IntuneDocs.nl-nl#98]
Hi, according to this article you cannot enroll a device with a DEM account who is also enrolled with DEP. I put this to the test, and the device seems working fine and shows up as 'supervised' I've used the enrollment via Company Portal instead of the Apple Wizard. What are the current limitations? 

---
#### Documentdetails

⚠ *Dit gedeelte niet bewerken. Het is vereist om problemen te koppelen tussen docs.microsoft.com en GitHub.*

* ID: 66328793-3fbd-dae1-6091-66d0690c71d6
* Version Independent ID: 5400708a-1e92-82ab-3199-6798fd1d5d6c
* Content: [Apparaten inschrijven met een apparaatinschrijvingsmanageraccount](https://docs.microsoft.com/nl-nl/intune/device-enrollment-manager-enroll)
* Content Source: [intune/device-enrollment-manager-enroll.md](https://github.com/MicrosoftDocs/IntuneDocs.nl-nl/blob/live/intune/device-enrollment-manager-enroll.md)
* Service: **microsoft-intune**
* Product: ****
* GitHub Login: @ErikjeMS
* Microsoft Alias: **erikje**

**Comment by LisandroSu** [comment]
Hello, @JanBakker88 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
